//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ActiveAssistant : NSObject
{
    int _MemoryWarningCount;
    double _startPower;
    double _endPower;
    unsigned long long _cellularDataRestrictedState;
}

+ (id)activeMonitor;
@property(nonatomic) unsigned long long cellularDataRestrictedState; // @synthesize cellularDataRestrictedState=_cellularDataRestrictedState;
@property(nonatomic) double endPower; // @synthesize endPower=_endPower;
@property(nonatomic) double startPower; // @synthesize startPower=_startPower;
@property(nonatomic) int MemoryWarningCount; // @synthesize MemoryWarningCount=_MemoryWarningCount;
- (id)getAppAuthorization;
- (id)proxySetting;
- (_Bool)checkProxySetting;
- (double)getEndPower;
- (double)getStartPower;
- (double)getCurrentPower;
- (double)getSetarTime;
- (void)setSetarTime:(double)arg1;
- (void)handleEnterBackground;
- (int)memoryWarningCount;
- (void)handleMemoryWarning;

@end

