//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "LCAdvertisingProtocol-Protocol.h"
#import "LCAnalyicsProtocol-Protocol.h"
#import "LCQualityDelegate-Protocol.h"
#import "LCUserProtocol-Protocol.h"
#import "QKAPNSProtocol-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"
#import "UNUserNotificationCenterDelegate-Protocol.h"

@class NSString, Steps, UIWindow, UserNotificationHandler;

@interface AppDelegate : UIResponder <LCAnalyicsProtocol, LCQualityDelegate, LCUserProtocol, LCAdvertisingProtocol, QKAPNSProtocol, UIApplicationDelegate, UNUserNotificationCenterDelegate>
{
    _Bool _is_show_root;
    _Bool _needForceShowRedEnvelope;
    UIWindow *_window;
    id _webview;
    Steps *_launchSteps;
    UserNotificationHandler *_apnsHandler;
}

@property(readonly, nonatomic) UserNotificationHandler *apnsHandler; // @synthesize apnsHandler=_apnsHandler;
@property(nonatomic) _Bool needForceShowRedEnvelope; // @synthesize needForceShowRedEnvelope=_needForceShowRedEnvelope;
@property(nonatomic) _Bool is_show_root; // @synthesize is_show_root=_is_show_root;
@property(retain, nonatomic) Steps *launchSteps; // @synthesize launchSteps=_launchSteps;
@property(retain, nonatomic) id webview; // @synthesize webview=_webview;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)webPageShowStatusBridge:(_Bool)arg1;
- (long long)networkStatus;
- (void)networkStatus:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)showRootController:(_Bool)arg1;
- (void)showRootController;
- (id)isExitClipBoardGift;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)initMemberTagsEnvironment:(id)arg1;
- (void)setupUMAnalytics;
- (void)QKShareConfig;
- (void)WebConfig;
- (void)UIConfig;
- (void)innoConfig:(_Bool)arg1;
- (void)suspect_and_reportWithHandler:(CDUnknownBlockType)arg1;
- (void)launchConfig;
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)userNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (void)qkPushConfig;
- (void)uPushConfig;
- (void)jPushConfig;
- (void)setupLCBase;
- (id)advertising_locationDate;
- (double)advertising_longitude;
- (double)advertising_latitude;
- (void)setupAdvertising;
- (void)setTagForRemoteNotification;
- (void)setAliasForRemoteNotification;
- (_Bool)isAllowedAPNSNotification;
- (void)setupLCUser;
- (id)currentPageInfo;
- (id)launchStyle;
- (id)appColdConfig;
- (id)appConfig;
- (id)userInfo;
- (id)getExtraInfo;
- (id)getUserId;
- (void)setupQuality;
- (id)userId;
- (id)network;
- (id)locationDate;
- (double)longitude;
- (double)latitude;
- (id)innoToken;
- (id)UUID;
- (id)AKU;
- (id)IDFA;
- (void)setupAnalyics;
- (void)setupPods;
- (void)initWebParam:(id)arg1;
- (void)notification_initialize_position:(id)arg1;
- (void)notification_initialize_show:(id)arg1;
- (void)notification_initialize:(id)arg1;
- (void)addNotification_initialize;
- (void)schemesAction:(id)arg1;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 handleOpenURL:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

