//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface AttributeAlertView : UIView
{
    _Bool _canNotTouchBack;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UIView *_btnTopLine;
    CDUnknownBlockType _alertClick;
    UIView *_contentView;
    UIView *_btnView;
}

@property(retain, nonatomic) UIView *btnView; // @synthesize btnView=_btnView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) _Bool canNotTouchBack; // @synthesize canNotTouchBack=_canNotTouchBack;
@property(copy, nonatomic) CDUnknownBlockType alertClick; // @synthesize alertClick=_alertClick;
@property(retain, nonatomic) UIView *btnTopLine; // @synthesize btnTopLine=_btnTopLine;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)show;
- (void)alertBtnOnClick:(id)arg1;
- (void)setBackColor:(id)arg1 textColor:(id)arg2 textFont:(float)arg3 withText:(id)arg4;
- (void)initChildViewsTitle:(id)arg1 message:(id)arg2 attributeMessage:(id)arg3 btnArray:(id)arg4;
- (id)initWithTitle:(id)arg1 message:(id)arg2 attributeMessage:(id)arg3 btnArray:(id)arg4 alertClick:(CDUnknownBlockType)arg5;

@end

