//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface CopyableLabel : UILabel
{
    _Bool _isCopyable;
}

@property(nonatomic) _Bool isCopyable; // @synthesize isCopyable=_isCopyable;
- (_Bool)canBecomeFirstResponder;
- (void)copyString:(id)arg1;
- (void)tap:(id)arg1;
- (void)attachTapHandler;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;

@end

