//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSMutableArray, NSString;

@interface FloatPicModel : LCBaseModel
{
    int _source;
    int _weight;
    int _floatListViewPosition;
    NSString *_start_time;
    NSString *_end_time;
    NSString *_picUrl;
    NSString *_platform;
    NSString *_title;
    NSMutableArray *_showTimeArray;
    NSString *_url;
}

@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSMutableArray *showTimeArray; // @synthesize showTimeArray=_showTimeArray;
@property(nonatomic) int floatListViewPosition; // @synthesize floatListViewPosition=_floatListViewPosition;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *platform; // @synthesize platform=_platform;
@property(copy, nonatomic) NSString *picUrl; // @synthesize picUrl=_picUrl;
@property(nonatomic) int weight; // @synthesize weight=_weight;
@property(copy, nonatomic) NSString *end_time; // @synthesize end_time=_end_time;
@property(copy, nonatomic) NSString *start_time; // @synthesize start_time=_start_time;
@property(nonatomic) int source; // @synthesize source=_source;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

