//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSMutableArray;

@interface FloatListModel : LCBaseModel
{
    float _closeHour;
    long long _currentTime;
    NSMutableArray *_floatPicArray;
    NSMutableArray *_imageArray;
    long long _updateTime;
}

@property(nonatomic) long long updateTime; // @synthesize updateTime=_updateTime;
@property(retain, nonatomic) NSMutableArray *imageArray; // @synthesize imageArray=_imageArray;
@property(retain, nonatomic) NSMutableArray *floatPicArray; // @synthesize floatPicArray=_floatPicArray;
@property(nonatomic) float closeHour; // @synthesize closeHour=_closeHour;
@property(nonatomic) long long currentTime; // @synthesize currentTime=_currentTime;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

