//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString;

@interface FloatShowTimeModel : LCBaseModel
{
    NSString *_show_start_time;
    NSString *_show_end_time;
}

@property(copy, nonatomic) NSString *show_end_time; // @synthesize show_end_time=_show_end_time;
@property(copy, nonatomic) NSString *show_start_time; // @synthesize show_start_time=_show_start_time;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

