//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface LaunchInfo : NSObject
{
    _Bool _isProxy;
    double _premainToMainTime;
    double _coldStartTime;
    double _warmStartTime;
    double _startPower;
    double _endPower;
}

+ (id)sharedInfo;
@property(nonatomic) _Bool isProxy; // @synthesize isProxy=_isProxy;
@property(nonatomic) double endPower; // @synthesize endPower=_endPower;
@property(nonatomic) double startPower; // @synthesize startPower=_startPower;
@property(nonatomic) double warmStartTime; // @synthesize warmStartTime=_warmStartTime;
@property(nonatomic) double coldStartTime; // @synthesize coldStartTime=_coldStartTime;
@property(nonatomic) double premainToMainTime; // @synthesize premainToMainTime=_premainToMainTime;

@end

