//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class LCFileStorage, NSMutableDictionary;

@interface LCCache : NSObject
{
    LCFileStorage *_fileStorage;
    NSMutableDictionary *_dataBaseMutableDic;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *dataBaseMutableDic; // @synthesize dataBaseMutableDic=_dataBaseMutableDic;
@property(retain, nonatomic) LCFileStorage *fileStorage; // @synthesize fileStorage=_fileStorage;
- (void).cxx_destruct;
- (id)dataBaseSqliteName:(id)arg1 folderPath:(id)arg2;
- (id)dataBaseSqliteName:(id)arg1;
- (id)init;

@end

