//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface LCQualityMonitorItem : NSObject
{
    NSString *_key;
    NSString *_title;
    CDUnknownBlockType _subtitle;
    CDUnknownBlockType _info;
    CDUnknownBlockType _badge;
}

@property(copy, nonatomic) CDUnknownBlockType badge; // @synthesize badge=_badge;
@property(copy, nonatomic) CDUnknownBlockType info; // @synthesize info=_info;
@property(copy, nonatomic) CDUnknownBlockType subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (id)initWithKey:(id)arg1 title:(id)arg2 subTitle:(CDUnknownBlockType)arg3 badge:(CDUnknownBlockType)arg4 info:(CDUnknownBlockType)arg5;

@end

