//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface LCQualityMonitorConfig : NSObject
{
    _Bool _showPerformancePanel;
    _Bool _shakeEnable;
    _Bool _monitorEnable;
    long long _mode;
}

@property(nonatomic) _Bool monitorEnable; // @synthesize monitorEnable=_monitorEnable;
@property(nonatomic) _Bool shakeEnable; // @synthesize shakeEnable=_shakeEnable;
@property(nonatomic) _Bool showPerformancePanel; // @synthesize showPerformancePanel=_showPerformancePanel;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
- (id)initWithGlobalMonitorEnable:(_Bool)arg1;
- (id)initWithMode:(long long)arg1;

@end

