//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface LCQualityMonitorGroup : NSObject
{
    NSString *_groupKey;
    NSString *_groupTitle;
    NSArray *_items;
}

@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(copy, nonatomic) NSString *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(copy, nonatomic) NSString *groupKey; // @synthesize groupKey=_groupKey;
- (void).cxx_destruct;
- (id)initWithGroupKey:(id)arg1 groupTitle:(id)arg2 Items:(id)arg3;

@end

