//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class LCQualityMonitorConfig, NSMutableArray;

@interface LCQualityMonitor : NSObject
{
    _Bool _isMonitorShown;
    LCQualityMonitorConfig *_monitorConfig;
    NSMutableArray *_groupArray;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *groupArray; // @synthesize groupArray=_groupArray;
@property(nonatomic) _Bool isMonitorShown; // @synthesize isMonitorShown=_isMonitorShown;
@property(retain, nonatomic) LCQualityMonitorConfig *monitorConfig; // @synthesize monitorConfig=_monitorConfig;
- (void).cxx_destruct;
- (id)_getMonitorViewController;
- (void)addMonitorGroup:(id)arg1;
- (void)showMonitor;
- (void)showMonitorPanel:(_Bool)arg1;
- (void)startWithGlobalMonitorEnable:(_Bool)arg1;
- (void)startWithMode:(long long)arg1;
- (id)init;

@end

