//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface LCSensorsAnalytics : NSObject
{
}

+ (void)setLogout;
+ (void)setLogin:(id)arg1;
+ (void)setupSensorsAnalyticsChannelId:(id)arg1;
+ (void)trackTimerEnd:(id)arg1 withProperties:(id)arg2;
+ (void)trackTimerBegin:(id)arg1;
+ (void)track:(id)arg1 withProperties:(id)arg2;
+ (void)initializeSensorsAnalyticsSDK;

@end

