//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSMutableDictionary;

@interface LCSystem : NSObject
{
    NSMutableDictionary *_m_services;
}

+ (id)serviceOfClass:(Class)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *m_services; // @synthesize m_services=_m_services;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *services;
- (void)clearAllServices;
- (void)removeServiceWithIdentifier:(id)arg1;
- (void)addService:(id)arg1;
- (_Bool)containServiceWithIdentifier:(id)arg1;
- (id)serviceWithIdentifier:(id)arg1;
- (id)init;

@end

