//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarController.h>

@interface LCTabbarController : UITabBarController
{
}

- (void)checkTabbarUpdateAndChange;
- (unsigned long long)indexWithKey:(id)arg1;
- (void)gotoHomeFromViewController:(id)arg1;
- (void)reloadHomeFromViewController:(id)arg1;
- (_Bool)containsMission;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

