//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MonitorBaseViewController.h"

#import "LCActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSDictionary, NSString, UITableView;

@interface MonitorViewController : MonitorBaseViewController <UITableViewDelegate, UITableViewDataSource, LCActionSheetDelegate>
{
    NSDictionary *_currentPageInfo;
    UITableView *_tableView;
    NSArray *_dataSource;
    NSArray *_sectionTitleArray;
    NSArray *_customizeDataSrouce;
    NSArray *_stucks;
    NSArray *_exceptions;
    NSArray *_leaks;
    long long _videoFailedCount;
}

@property(nonatomic) long long videoFailedCount; // @synthesize videoFailedCount=_videoFailedCount;
@property(retain, nonatomic) NSArray *leaks; // @synthesize leaks=_leaks;
@property(retain, nonatomic) NSArray *exceptions; // @synthesize exceptions=_exceptions;
@property(retain, nonatomic) NSArray *stucks; // @synthesize stucks=_stucks;
@property(copy, nonatomic) NSArray *customizeDataSrouce; // @synthesize customizeDataSrouce=_customizeDataSrouce;
@property(copy, nonatomic) NSArray *sectionTitleArray; // @synthesize sectionTitleArray=_sectionTitleArray;
@property(copy, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSDictionary *currentPageInfo; // @synthesize currentPageInfo=_currentPageInfo;
- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)debug_apis;
- (void)showApi;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)switchAction:(id)arg1;
- (void)backAction:(id)arg1;
- (void)setupCustomizeMonitorGroups:(id)arg1;
- (void)layoutUI;
- (void)createUI;
- (void)setupUI;
- (void)setupParam;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

