//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MonitorBaseViewController.h"

#import "UITextViewDelegate-Protocol.h"

@class NSString, UITextView;

@interface MonitorTextViewController : MonitorBaseViewController <UITextViewDelegate>
{
    UITextView *_textView;
}

@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
- (void)addInfo:(id)arg1;
- (void)setupFont:(id)arg1;
- (void)setupText:(id)arg1;
- (void)setupInfo:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

