//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface PageInfo : NSObject
{
    NSMutableArray *_pages;
    long long _videoPlayerSuccessCount;
    long long _videoPlayerFailedCount;
}

+ (id)sharedInfo;
@property(nonatomic) long long videoPlayerFailedCount; // @synthesize videoPlayerFailedCount=_videoPlayerFailedCount;
@property(nonatomic) long long videoPlayerSuccessCount; // @synthesize videoPlayerSuccessCount=_videoPlayerSuccessCount;
@property(retain, nonatomic) NSMutableArray *pages; // @synthesize pages=_pages;
- (void).cxx_destruct;
- (long long)getVideoPlayerFailedCount;
- (long long)getVideoPlayerSuccessCount;
- (void)videoPlayerInitFailed;
- (void)videoPlayerInitSuccessfully;
- (id)vcClassNameOfPage:(id)arg1;
- (id)performanceInfoOfPage:(id)arg1;
- (id)loadInfoOfPage:(id)arg1;
- (id)getAllWebPages;
- (id)getAllPages;
- (void)addPage:(id)arg1;

@end

