//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MonitorBaseViewController.h"

#import "UITextViewDelegate-Protocol.h"

@class NSString, NSTimer, UILabel;

@interface PerformanceMonitorViewController : MonitorBaseViewController <UITextViewDelegate>
{
    UILabel *_cpuLabel;
    UILabel *_memLabel;
    UILabel *_fpsLabel;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UILabel *fpsLabel; // @synthesize fpsLabel=_fpsLabel;
@property(retain, nonatomic) UILabel *memLabel; // @synthesize memLabel=_memLabel;
@property(retain, nonatomic) UILabel *cpuLabel; // @synthesize cpuLabel=_cpuLabel;
- (void).cxx_destruct;
- (void)timerAction:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)configData;
- (void)layoutUI;
- (void)createUI;
- (void)setupParam;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

