//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer, UILabel;

@interface PerformanceMonitorPanel : UIView
{
    _Bool isMove;
    struct CGPoint legend_point;
    UILabel *_fpsLabel;
    UILabel *_cpuLabel;
    UILabel *_memLabel;
    UILabel *_powerLabel;
    NSTimer *_timer;
}

+ (id)monitorPanel;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UILabel *powerLabel; // @synthesize powerLabel=_powerLabel;
@property(retain, nonatomic) UILabel *memLabel; // @synthesize memLabel=_memLabel;
@property(retain, nonatomic) UILabel *cpuLabel; // @synthesize cpuLabel=_cpuLabel;
@property(retain, nonatomic) UILabel *fpsLabel; // @synthesize fpsLabel=_fpsLabel;
- (void).cxx_destruct;
- (void)timerAction:(id)arg1;
- (void)doMoveAction:(id)arg1;
- (void)layoutSubviews;
- (void)createUI;
- (void)setupUI;
- (void)setupParam;
- (id)initWithFrame:(struct CGRect)arg1;

@end

