//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface QKNewShareModel : NSObject
{
    NSString *_title;
    NSString *_desc;
    NSNumber *_target;
    NSString *_type;
    NSString *_icon;
    NSArray *_pics;
    NSString *_wayType;
    NSString *_wxAppid;
    NSString *_url;
    NSString *_currentTime;
    NSString *_contentID;
}

@property(copy, nonatomic) NSString *contentID; // @synthesize contentID=_contentID;
@property(copy, nonatomic) NSString *currentTime; // @synthesize currentTime=_currentTime;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *wxAppid; // @synthesize wxAppid=_wxAppid;
@property(copy, nonatomic) NSString *wayType; // @synthesize wayType=_wayType;
@property(copy, nonatomic) NSArray *pics; // @synthesize pics=_pics;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSNumber *target; // @synthesize target=_target;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

