//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSDictionary, NSString;

@interface QKReadAntiCheatingModel : LCBaseModel
{
    _Bool _enable;
    _Bool _isRed;
    _Bool _isShow;
    int _redHintPosition;
    int _timeType;
    double _read_length_limit;
    NSString *_read_length_limit_tips;
    NSString *_read_times_limit_tips;
    double _read_multiple;
    double _read_rate;
    double _read_random;
    double _timeCoe;
    NSString *_redTips;
    double _videoTimeCoe;
    NSDictionary *_redDict;
}

@property(retain, nonatomic) NSDictionary *redDict; // @synthesize redDict=_redDict;
@property(nonatomic) double videoTimeCoe; // @synthesize videoTimeCoe=_videoTimeCoe;
@property(copy, nonatomic) NSString *redTips; // @synthesize redTips=_redTips;
@property(nonatomic) double timeCoe; // @synthesize timeCoe=_timeCoe;
@property(nonatomic) int timeType; // @synthesize timeType=_timeType;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
@property(nonatomic) _Bool isRed; // @synthesize isRed=_isRed;
@property(nonatomic) int redHintPosition; // @synthesize redHintPosition=_redHintPosition;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
@property(nonatomic) double read_random; // @synthesize read_random=_read_random;
@property(nonatomic) double read_rate; // @synthesize read_rate=_read_rate;
@property(nonatomic) double read_multiple; // @synthesize read_multiple=_read_multiple;
@property(copy, nonatomic) NSString *read_times_limit_tips; // @synthesize read_times_limit_tips=_read_times_limit_tips;
@property(copy, nonatomic) NSString *read_length_limit_tips; // @synthesize read_length_limit_tips=_read_length_limit_tips;
@property(nonatomic) double read_length_limit; // @synthesize read_length_limit=_read_length_limit;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

