//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface QKSignFloatingView : UIView
{
    _Bool _shouldRemoveFlaotingView;
    _Bool _hasShowedFloatingView;
    long long _taskIndex;
}

+ (_Bool)checkIfShowedFloatingView;
+ (id)sharedSignFloatingView;
+ (void)configFloatingView;
@property(nonatomic) _Bool hasShowedFloatingView; // @synthesize hasShowedFloatingView=_hasShowedFloatingView;
@property(nonatomic) long long taskIndex; // @synthesize taskIndex=_taskIndex;
@property(nonatomic) _Bool shouldRemoveFlaotingView; // @synthesize shouldRemoveFlaotingView=_shouldRemoveFlaotingView;
- (void)removeFloatingView;
- (void)setShowedFloatingView;
- (void)checkIfShouldShowFloatingView;
- (void)removeNoti:(id)arg1;
- (void)loginNoti:(id)arg1;
- (void)coldConfigNoti:(id)arg1;
- (void)tapAction:(id)arg1;
- (void)configObserver;

@end

