//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CAAnimationDelegate-Protocol.h"

@class NSString, UIImageView, UILabel;

@interface RedTimeAnimationView : UIView <CAAnimationDelegate>
{
    UIImageView *_timerImageView;
    UIImageView *_animationWhithView;
    UIImageView *_animationCoinView;
    UILabel *_animationCoinLabel;
    UIView *_coinBackView;
}

@property(retain, nonatomic) UIView *coinBackView; // @synthesize coinBackView=_coinBackView;
@property(retain, nonatomic) UILabel *animationCoinLabel; // @synthesize animationCoinLabel=_animationCoinLabel;
@property(retain, nonatomic) UIImageView *animationCoinView; // @synthesize animationCoinView=_animationCoinView;
@property(retain, nonatomic) UIImageView *animationWhithView; // @synthesize animationWhithView=_animationWhithView;
@property(retain, nonatomic) UIImageView *timerImageView; // @synthesize timerImageView=_timerImageView;
- (void).cxx_destruct;
- (void)keyframeAnimation:(id)arg1 animationKeyPath:(id)arg2 values:(id)arg3 keyTimes:(id)arg4 duration:(double)arg5 key:(id)arg6;
- (void)basicAnimation:(id)arg1 animationKeyPath:(id)arg2 fromValue:(id)arg3 toValue:(id)arg4 duration:(double)arg5 key:(id)arg6;
- (void)timerImageViewAnimationWithCoinValue:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)updateUI;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

