//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface RequestApi : NSObject
{
    NSArray *_requests;
    long long _successTimes;
    long long _failedTimes;
    NSString *_api;
}

@property(copy, nonatomic) NSString *api; // @synthesize api=_api;
@property(nonatomic) long long failedTimes; // @synthesize failedTimes=_failedTimes;
@property(nonatomic) long long successTimes; // @synthesize successTimes=_successTimes;
@property(retain, nonatomic) NSArray *requests; // @synthesize requests=_requests;
- (void).cxx_destruct;

@end

