//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface StuckInfo : NSObject
{
    NSMutableArray *_fillModels;
}

+ (id)sharedInfo;
@property(retain, nonatomic) NSMutableArray *fillModels; // @synthesize fillModels=_fillModels;
- (void).cxx_destruct;
- (id)sortedArrayFromDict:(id)arg1;
- (id)dictionaryFromFillModels:(id)arg1 byKey:(id)arg2;
- (id)getStuckFillModelsListByKey:(id)arg1 fromArray:(id)arg2;
- (id)getAllStuckFillModels;
- (void)addStuckFillModel:(id)arg1;

@end

