//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MonitorTextViewController.h"

@class FillModel;

@interface StuckDetailViewController : MonitorTextViewController
{
    FillModel *_fillModel;
}

@property(retain, nonatomic) FillModel *fillModel; // @synthesize fillModel=_fillModel;
- (void).cxx_destruct;
- (void)initUI;
- (void)viewDidLoad;

@end

